export const UPDATE_PHOTO = 'update_photo'
export const USER_FETCH_SUCCESS = 'user_fetch_success'
export const ALL_USERS_FETCH_SUCCESS = 'all_users_fetch_success'
export const FRIENDS_FETCH_SUCCESS = 'friends_fetch_success'
export const NO_FRIENDS_FETCHED = 'no_friends_fetched'
